on: # yamllint disable-line rule:truthy
  push:
    branches: ["master"]

name: Create RPM Release

jobs:
  call-rpmbuild-workflow-for-rhel8:
    uses: fmidev/github-actions-workflows/.github/workflows/rpmbuild-workflow.yaml@main
    with:
      rpm_base_image: rockylinux/rockylinux:8
      rpm_spec_file: fmigrib.spec
      rpm_additional_repositories: "epel-release,https://download.fmi.fi/smartmet-open/rhel/8/x86_64/smartmet-open-release-latest-8.noarch.rpm"
      rpm_enable_repositories: powertools
      rpm_dnf_commands: "dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo && dnf config-manager --setopt='epel.exclude=eccodes*' --save"
      build_image: false
    secrets:
      RPM_API_HOST: ${{ secrets.RPM_API_HOST }}
      RPM_API_USER: ${{ secrets.RPM_API_USER }}
      RPM_API_PASS: ${{ secrets.RPM_API_PASS }}
  call-rpmbuild-workflow-for-rhel9:
    uses: fmidev/github-actions-workflows/.github/workflows/rpmbuild-workflow.yaml@main
    with:
      rpm_base_image: rockylinux/rockylinux:9
      rpm_spec_file: fmigrib.spec
      rpm_additional_repositories: "epel-release,https://download.fmi.fi/smartmet-open/rhel/9/x86_64/smartmet-open-release-latest-9.noarch.rpm"
      rpm_enable_repositories: crb
      rpm_dnf_commands: "dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo && dnf config-manager --setopt='epel.exclude=eccodes*' --save"
      build_image: false
    secrets:
      RPM_API_HOST: ${{ secrets.RPM_API_HOST_RHEL9 }}
      RPM_API_USER: ${{ secrets.RPM_API_USER }}
      RPM_API_PASS: ${{ secrets.RPM_API_PASS }}
